- hosts: flask
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      
    - name: Install Python 3 and Pip
      package:
        name: python3
        state: present
      when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'zypper'
          
    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Install OpenSSH
      package:
        name: openssh-server
        state: present
        
    - name: Install Git
      package:
        name: git
        state: present
        
    - name: Install Gunicorn
      pip:
        name: gunicorn
        state: present

    - name: Delete existing directory
      file:
        path: /home/ec2-user/ferari_website
        state: absent

    - name: Clone Git repository
      become: true
      git:
        repo: https://github.com/yotamdavid/ferari_website.git
        dest: /home/ec2-user/ferari_website
        accept_hostkey: yes

    - name: Copy flaskapp.service file
      copy:
        src: "/home/yotam/Desktop/ansible/ansible/flask_startup_template.j2"
        dest: "/etc/systemd/system/flaskapp.service"

    - name: Reload systemd daemon
      become: true
      command: systemctl daemon-reload

    - name: Restart Flask App service
      become: true
      command: systemctl restart flaskapp.service

    - name: Enable Flask App service on boot
      become: true
      command: systemctl enable flaskapp.service
