- hosts: localhost
  become: yes
  tasks:
    - name: Update package cache
      command: yum update -y

    - name: Install Python 3
      command: yum install -y python3

    - name: Install Pip
      command: yum install -y python3-pip

    - name: Install Flask
      command: pip3 install flask

    - name: Install Gunicorn
      command: pip3 install gunicorn

    - name: Install Git
      command: yum install -y git

    - name: Delete existing directory
      file:
        path: /home/ec2-user/profile_wabsite
        state: absent

    - name: Clone Git repository
      git:
        repo: https://github.com/yotamdavid/profile_wabsite.git
        dest: /home/ec2-user/
        accept_hostkey: yes

    - name: Copy flaskapp.service file
      copy:
        src: "/home/ec2-user/ansible/ansible/flask_startup_template.j2"
        dest: "/etc/systemd/system/flaskapp.service"

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Restart Flask App service
      command: systemctl restart flaskapp.service

    - name: Enable Flask App service on boot
      command: systemctl enable flaskapp.service
