- hosts: flask
  become: yes
  tasks:
    - name: Update package cache
      package:
        name: aptitude
        state: present
      when: ansible_pkg_mgr == 'apt'
      
    - name: Install python3-apt
      command: apt-get install -y python3-apt
      when: ansible_pkg_mgr == 'apt'

    - name: Install Python 3 and Pip
      package:
        name: python3-pip
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install pip
      become: true
      apt:
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Install Gunicorn
      pip:
        name: gunicorn
        state: present

    - name: Install Git
      package:
        name: git
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Clone Git repository
      git:
        repo: https://github.com/yotamdavid/ferari_website.git
        dest: /home/ec2-user/

    - name: Copy flaskapp.service file
      copy:
        src: "/home/yotam/Desktop/ansible/flask_startup_template.j2"
        dest: "/etc/systemd/system/flaskapp.service"

    - name: Reload systemd daemon
      become: true
      command: systemctl daemon-reload

    - name: Start Flask App service
      become: true
      command: systemctl start flaskapp.service

    - name: Enable Flask App service on boot
      become: true
      command: systemctl enable flaskapp.service
