---
- name: Install and configure SSH, Git, and Apache HTTP Server
  hosts: https
  become: true
  tasks:
    - name: Install SSH server, Git, and Apache HTTP Server
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - openssh-server
        - git
        - httpd
        - php

    - name: Start and enable SSH service
      service:
        name: sshd
        state: started
        enabled: true

    - name: Start and enable Apache HTTP Server
      service:
        name: httpd
        state: started
        enabled: true

    - name: Copy website files
      copy:
        src: index.html
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: 0644
