- hosts: flask
  become: yes
  tasks:
    - name: Update package cache (Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Update package cache (RedHat)
      dnf:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Install Python 3 and Pip (Debian)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
      when: ansible_os_family == 'Debian'

    - name: Install Python 3 and Pip (RedHat)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
      when: ansible_os_family == 'RedHat' and ansible_pkg_mgr == 'dnf'

    - name: Install Pip (Debian)
      package:
        name: python3-pip
        state: present
      when: ansible_os_family == 'Debian' and (ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'dnf')

    - name: Install Flask
      pip:
        name: flask
        state: present
      when: ansible_pkg_mgr == 'apt' or ansible_pkg_mgr == 'dnf'

    - name: Install Apache HTTP Server (httpd)
      package:
        name: httpd
        state: present
      when: ansible_pkg_mgr == 'dnf'

    - name: Install OpenSSH
      package:
        name: openssh-server
        state: present

    - name: Install Git
      package:
        name: git
        state: present

    - name: Install Gunicorn
      pip:
        name: gunicorn
        state: present

    - name: Clone Git repository
      git:
        repo: https://github.com/yotamdavid/ferari_website.git
        dest: /home/ec2-user/

    - name: Copy flaskapp.service file
      copy:
        src: "/home/yotam/Desktop/ansible/flask_startup_template.j2"
        dest: "/etc/systemd/system/flaskapp.service"

    - name: Reload systemd daemon
      become: true
      command: sudo systemctl daemon-reload

    - name: Start Flask App service
      become: true
      command: sudo systemctl start flaskapp.service

    - name: Enable Flask App service on boot
      become: true
      command: sudo systemctl enable flaskapp.service
