- hosts: flask
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Update package cache
      package:
        name: aptitude
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: Install Python 3 and Pip
      package:
        name: python3-pip
        state: present
      when: ansible_pkg_mgr == 'dnf'

    - name: Install Flask
      pip:
        name: flask
        state: present
      when: ansible_pkg_mgr == 'dnf'

    - name: Install Gunicorn
      pip:
        name: gunicorn
        state: present
      when: ansible_pkg_mgr == 'dnf'

    - name: Install Git
      package:
        name: git
        state: present
      when: ansible_pkg_mgr == 'dnf'

    - name: Delete existing directory
      file:
        path: /home/ec2-user/ferari_website
        state: absent

    - name: Clone Git repository
      become: true
      git:
        repo: https://github.com/yotamdavid/ferari_website.git
        dest: /home/ec2-user/ferari_website
        accept_hostkey: yes

    - name: Copy flaskapp.service file
      copy:
        src: "/home/yotam/Desktop/ansible/ansible/flask_startup_template.j2"
        dest: "/etc/systemd/system/flaskapp.service"

    - name: Reload systemd daemon
      become: true
      command: systemctl daemon-reload

    - name: Restart Flask App service
      become: true
      command: systemctl restart flaskapp.service

    - name: Enable Flask App service on boot
      become: true
      command: systemctl enable flaskapp.service
